name: Build wechotd image

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - branch: main
          tag: latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ matrix.branch }}

    - uses: docker/setup-buildx-action@v3.6.1

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v6.5.0
      with:
        context: ./
        file: Dockerfile
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push: true
        provenance: false
        platforms: linux/amd64, linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}/wechotd:${{ matrix.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max